spring:
  application:
    name: client-service
  config:
    import: "optional:configserver:http://localhost:8081"
  datasource:
    url: jdbc:postgresql://localhost:5432/ToolRent-client
    username: postgres
    password: Almeria12!
  jpa:
    hibernate:
      ddl-auto: update