spring:
  application:
    name: rent-service
  config:
    import: "optional:configserver:http://localhost:8081"
  datasource:
    url: jdbc:postgresql://localhost:5432/ToolRent-rent
    username: postgres
    password: Almeria12!
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/toolrent-realm